swagger: '2.0'
info:
  title: api-gateway
  version: 1.0.0
basePath: /
schemes:
  - https
paths:
  /courses:
    get:
      summary: Get all courses
      operationId: getCourses
      x-google-backend:
        address: https://us-central1-syscourse-474.cloudfunctions.net/course_helper/courses
      responses:
        '200':
          description: A list of courses
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
    post:
      summary: Add a new course
      operationId: addCourses
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Course'
      x-google-backend:
        address: https://us-central1-syscourse-474.cloudfunctions.net/course_helper/courses
      responses:
        '201':
          description: Course added successfully
  
  /resources:
    get:
      summary: Get all resources
      operationId: getResources
      x-google-backend:
        address: https://us-central1-syscourse-474.cloudfunctions.net/flask_app/resources
      responses:
        '200':
          description: A list of resources
          schema:
            type: array
            items:
              $ref: '#/definitions/Resource'
    post:
      summary: Add a new resource
      operationId: addResources
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Resource'
      x-google-backend:
        address: https://us-central1-syscourse-474.cloudfunctions.net/flask_app/resources
      responses:
        '201':
          description: Resource added successfully

definitions:
  Course:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      instructor:
        type: string
      field:
        type: string
      level:
        type: string
      language:
        type: string
      thumbnailUrl:
        type: string
      uid:
        type: string
      ratingsAverage:
        type: number
      ratingsCount:
        type: integer
      document_id:
        type: string
      course_id:
        type: string

  Resource:
    type: object
    properties:
      course_id:
        type: string
      title:
        type: string
      type:
        type: string
      url:
        type: string
      description:
        type: string
      uid:
        type: string
      duration: 
        type: integer
      document_id: 
        type: string
      resource_id: 
        type: string